CREATE DATABASE `Smart Wallet`;
USE `Smart Wallet`;

CREATE TABLE incomes
(
	id INT PRIMARY KEY AUTO_INCREMENT,
	amount DECIMAL(10,2) NOT NULL,
	description TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE expenses
(
	id INT PRIMARY KEY AUTO_INCREMENT,
	amount DECIMAL(10,2) NOT NULL,
	description TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);



